### ISSUE TITLE
Nice job! could use a little work

### ISSUE THREAD

**Issue by peterson542** [davidhrbaty/ArduBot#1]
WOW    im impressed! nice job on this, would like to see if you could switch modes with only one button. is there a way to fix the timer conflict between newping and ir remote? that would be alot easier to use. thanks!

**Comment by davidhrbaty** [comment]
Hello, I do not plan to switch modes with only one button, but it is easy to modify this code to use with only one button. 
Conflict between newping and ir remote library is due to limit of hardware. On atmega 328 processor is only two timers, so one is used for timing servos and second is used to timing IR remotes, so therefore I cannot use newping library. You can migrate Ardubot to atmega 2560 and then you can use these libraries at the same time

**Comment by andrequeiroz2** [comment]
hello David this project and incredible . I would use it in a science fair . I have a doubt about the remote control, which control can I use?

thanks, hugs
